<?php
/**
 * DrivingTimeRegulationLogbookSummaryEUEC5612006
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * xServer
 *
 * PTV xServer 2.26.0 - 2.26 API document
 *
 * OpenAPI spec version: 2.26
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.34
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Model;
use \Swagger\Client\ObjectSerializer;

/**
 * DrivingTimeRegulationLogbookSummaryEUEC5612006 Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class DrivingTimeRegulationLogbookSummaryEUEC5612006 extends DrivingTimeRegulationLogbookSummary 
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'DrivingTimeRegulationLogbookSummary_EU_EC_561_2006';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'accumulated_driving_time_since_last_break' => '\Swagger\Client\Model\Duration',
'accumulated_driving_time_since_last_daily_rest' => '\Swagger\Client\Model\Duration',
'elapsed_time_since_end_of_last_daily_rest' => '\Swagger\Client\Model\Duration'    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'accumulated_driving_time_since_last_break' => null,
'accumulated_driving_time_since_last_daily_rest' => null,
'elapsed_time_since_end_of_last_daily_rest' => null    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes + parent::swaggerTypes();
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats + parent::swaggerFormats();
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'accumulated_driving_time_since_last_break' => 'accumulatedDrivingTimeSinceLastBreak',
'accumulated_driving_time_since_last_daily_rest' => 'accumulatedDrivingTimeSinceLastDailyRest',
'elapsed_time_since_end_of_last_daily_rest' => 'elapsedTimeSinceEndOfLastDailyRest'    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'accumulated_driving_time_since_last_break' => 'setAccumulatedDrivingTimeSinceLastBreak',
'accumulated_driving_time_since_last_daily_rest' => 'setAccumulatedDrivingTimeSinceLastDailyRest',
'elapsed_time_since_end_of_last_daily_rest' => 'setElapsedTimeSinceEndOfLastDailyRest'    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'accumulated_driving_time_since_last_break' => 'getAccumulatedDrivingTimeSinceLastBreak',
'accumulated_driving_time_since_last_daily_rest' => 'getAccumulatedDrivingTimeSinceLastDailyRest',
'elapsed_time_since_end_of_last_daily_rest' => 'getElapsedTimeSinceEndOfLastDailyRest'    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return parent::attributeMap() + self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return parent::setters() + self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return parent::getters() + self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    


    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        parent::__construct($data);

        $this->container['accumulated_driving_time_since_last_break'] = isset($data['accumulated_driving_time_since_last_break']) ? $data['accumulated_driving_time_since_last_break'] : null;
        $this->container['accumulated_driving_time_since_last_daily_rest'] = isset($data['accumulated_driving_time_since_last_daily_rest']) ? $data['accumulated_driving_time_since_last_daily_rest'] : null;
        $this->container['elapsed_time_since_end_of_last_daily_rest'] = isset($data['elapsed_time_since_end_of_last_daily_rest']) ? $data['elapsed_time_since_end_of_last_daily_rest'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = parent::listInvalidProperties();

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets accumulated_driving_time_since_last_break
     *
     * @return \Swagger\Client\Model\Duration
     */
    public function getAccumulatedDrivingTimeSinceLastBreak()
    {
        return $this->container['accumulated_driving_time_since_last_break'];
    }

    /**
     * Sets accumulated_driving_time_since_last_break
     *
     * @param \Swagger\Client\Model\Duration $accumulated_driving_time_since_last_break accumulated_driving_time_since_last_break
     *
     * @return $this
     */
    public function setAccumulatedDrivingTimeSinceLastBreak($accumulated_driving_time_since_last_break)
    {
        $this->container['accumulated_driving_time_since_last_break'] = $accumulated_driving_time_since_last_break;

        return $this;
    }

    /**
     * Gets accumulated_driving_time_since_last_daily_rest
     *
     * @return \Swagger\Client\Model\Duration
     */
    public function getAccumulatedDrivingTimeSinceLastDailyRest()
    {
        return $this->container['accumulated_driving_time_since_last_daily_rest'];
    }

    /**
     * Sets accumulated_driving_time_since_last_daily_rest
     *
     * @param \Swagger\Client\Model\Duration $accumulated_driving_time_since_last_daily_rest accumulated_driving_time_since_last_daily_rest
     *
     * @return $this
     */
    public function setAccumulatedDrivingTimeSinceLastDailyRest($accumulated_driving_time_since_last_daily_rest)
    {
        $this->container['accumulated_driving_time_since_last_daily_rest'] = $accumulated_driving_time_since_last_daily_rest;

        return $this;
    }

    /**
     * Gets elapsed_time_since_end_of_last_daily_rest
     *
     * @return \Swagger\Client\Model\Duration
     */
    public function getElapsedTimeSinceEndOfLastDailyRest()
    {
        return $this->container['elapsed_time_since_end_of_last_daily_rest'];
    }

    /**
     * Sets elapsed_time_since_end_of_last_daily_rest
     *
     * @param \Swagger\Client\Model\Duration $elapsed_time_since_end_of_last_daily_rest elapsed_time_since_end_of_last_daily_rest
     *
     * @return $this
     */
    public function setElapsedTimeSinceEndOfLastDailyRest($elapsed_time_since_end_of_last_daily_rest)
    {
        $this->container['elapsed_time_since_end_of_last_daily_rest'] = $elapsed_time_since_end_of_last_daily_rest;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}
