<?php
/**
 * InsertionPositionsForOrdersQuery
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * xServer
 *
 * PTV xServer 2.26.0 - 2.26 API document
 *
 * OpenAPI spec version: 2.26
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.34
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Model;
use \Swagger\Client\ObjectSerializer;

/**
 * InsertionPositionsForOrdersQuery Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class InsertionPositionsForOrdersQuery extends ChangeToursProposalsQuery 
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'InsertionPositionsForOrdersQuery';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'order_ids' => 'string[]',
'target_vehicle_ids' => 'string[]',
'maximum_number_of_move_orders_actions' => '\Swagger\Client\Model\NonNegativeInteger',
'maximum_distance_of_adjacent_stops' => '\Swagger\Client\Model\Distance'    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'order_ids' => null,
'target_vehicle_ids' => null,
'maximum_number_of_move_orders_actions' => null,
'maximum_distance_of_adjacent_stops' => null    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes + parent::swaggerTypes();
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats + parent::swaggerFormats();
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'order_ids' => 'orderIds',
'target_vehicle_ids' => 'targetVehicleIds',
'maximum_number_of_move_orders_actions' => 'maximumNumberOfMoveOrdersActions',
'maximum_distance_of_adjacent_stops' => 'maximumDistanceOfAdjacentStops'    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'order_ids' => 'setOrderIds',
'target_vehicle_ids' => 'setTargetVehicleIds',
'maximum_number_of_move_orders_actions' => 'setMaximumNumberOfMoveOrdersActions',
'maximum_distance_of_adjacent_stops' => 'setMaximumDistanceOfAdjacentStops'    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'order_ids' => 'getOrderIds',
'target_vehicle_ids' => 'getTargetVehicleIds',
'maximum_number_of_move_orders_actions' => 'getMaximumNumberOfMoveOrdersActions',
'maximum_distance_of_adjacent_stops' => 'getMaximumDistanceOfAdjacentStops'    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return parent::attributeMap() + self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return parent::setters() + self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return parent::getters() + self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    


    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        parent::__construct($data);

        $this->container['order_ids'] = isset($data['order_ids']) ? $data['order_ids'] : null;
        $this->container['target_vehicle_ids'] = isset($data['target_vehicle_ids']) ? $data['target_vehicle_ids'] : null;
        $this->container['maximum_number_of_move_orders_actions'] = isset($data['maximum_number_of_move_orders_actions']) ? $data['maximum_number_of_move_orders_actions'] : null;
        $this->container['maximum_distance_of_adjacent_stops'] = isset($data['maximum_distance_of_adjacent_stops']) ? $data['maximum_distance_of_adjacent_stops'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = parent::listInvalidProperties();

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets order_ids
     *
     * @return string[]
     */
    public function getOrderIds()
    {
        return $this->container['order_ids'];
    }

    /**
     * Sets order_ids
     *
     * @param string[] $order_ids order_ids
     *
     * @return $this
     */
    public function setOrderIds($order_ids)
    {
        $this->container['order_ids'] = $order_ids;

        return $this;
    }

    /**
     * Gets target_vehicle_ids
     *
     * @return string[]
     */
    public function getTargetVehicleIds()
    {
        return $this->container['target_vehicle_ids'];
    }

    /**
     * Sets target_vehicle_ids
     *
     * @param string[] $target_vehicle_ids target_vehicle_ids
     *
     * @return $this
     */
    public function setTargetVehicleIds($target_vehicle_ids)
    {
        $this->container['target_vehicle_ids'] = $target_vehicle_ids;

        return $this;
    }

    /**
     * Gets maximum_number_of_move_orders_actions
     *
     * @return \Swagger\Client\Model\NonNegativeInteger
     */
    public function getMaximumNumberOfMoveOrdersActions()
    {
        return $this->container['maximum_number_of_move_orders_actions'];
    }

    /**
     * Sets maximum_number_of_move_orders_actions
     *
     * @param \Swagger\Client\Model\NonNegativeInteger $maximum_number_of_move_orders_actions maximum_number_of_move_orders_actions
     *
     * @return $this
     */
    public function setMaximumNumberOfMoveOrdersActions($maximum_number_of_move_orders_actions)
    {
        $this->container['maximum_number_of_move_orders_actions'] = $maximum_number_of_move_orders_actions;

        return $this;
    }

    /**
     * Gets maximum_distance_of_adjacent_stops
     *
     * @return \Swagger\Client\Model\Distance
     */
    public function getMaximumDistanceOfAdjacentStops()
    {
        return $this->container['maximum_distance_of_adjacent_stops'];
    }

    /**
     * Sets maximum_distance_of_adjacent_stops
     *
     * @param \Swagger\Client\Model\Distance $maximum_distance_of_adjacent_stops maximum_distance_of_adjacent_stops
     *
     * @return $this
     */
    public function setMaximumDistanceOfAdjacentStops($maximum_distance_of_adjacent_stops)
    {
        $this->container['maximum_distance_of_adjacent_stops'] = $maximum_distance_of_adjacent_stops;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}
