<?php
/**
 * MatchTrackRequest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * xServer
 *
 * PTV xServer 2.26.0 - 2.26 API document
 *
 * OpenAPI spec version: 2.26
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.34
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Model;
use \Swagger\Client\ObjectSerializer;

/**
 * MatchTrackRequest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class MatchTrackRequest extends RequestBase 
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'MatchTrackRequest';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'track_positions' => '\Swagger\Client\Model\TrackPosition[]',
'result_fields' => '\Swagger\Client\Model\MatchTrackResultFields',
'match_track_options' => '\Swagger\Client\Model\MatchTrackOptions'    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'track_positions' => null,
'result_fields' => null,
'match_track_options' => null    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes + parent::swaggerTypes();
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats + parent::swaggerFormats();
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'track_positions' => 'trackPositions',
'result_fields' => 'resultFields',
'match_track_options' => 'matchTrackOptions'    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'track_positions' => 'setTrackPositions',
'result_fields' => 'setResultFields',
'match_track_options' => 'setMatchTrackOptions'    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'track_positions' => 'getTrackPositions',
'result_fields' => 'getResultFields',
'match_track_options' => 'getMatchTrackOptions'    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return parent::attributeMap() + self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return parent::setters() + self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return parent::getters() + self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    


    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        parent::__construct($data);

        $this->container['track_positions'] = isset($data['track_positions']) ? $data['track_positions'] : null;
        $this->container['result_fields'] = isset($data['result_fields']) ? $data['result_fields'] : null;
        $this->container['match_track_options'] = isset($data['match_track_options']) ? $data['match_track_options'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = parent::listInvalidProperties();

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets track_positions
     *
     * @return \Swagger\Client\Model\TrackPosition[]
     */
    public function getTrackPositions()
    {
        return $this->container['track_positions'];
    }

    /**
     * Sets track_positions
     *
     * @param \Swagger\Client\Model\TrackPosition[] $track_positions track_positions
     *
     * @return $this
     */
    public function setTrackPositions($track_positions)
    {
        $this->container['track_positions'] = $track_positions;

        return $this;
    }

    /**
     * Gets result_fields
     *
     * @return \Swagger\Client\Model\MatchTrackResultFields
     */
    public function getResultFields()
    {
        return $this->container['result_fields'];
    }

    /**
     * Sets result_fields
     *
     * @param \Swagger\Client\Model\MatchTrackResultFields $result_fields result_fields
     *
     * @return $this
     */
    public function setResultFields($result_fields)
    {
        $this->container['result_fields'] = $result_fields;

        return $this;
    }

    /**
     * Gets match_track_options
     *
     * @return \Swagger\Client\Model\MatchTrackOptions
     */
    public function getMatchTrackOptions()
    {
        return $this->container['match_track_options'];
    }

    /**
     * Sets match_track_options
     *
     * @param \Swagger\Client\Model\MatchTrackOptions $match_track_options match_track_options
     *
     * @return $this
     */
    public function setMatchTrackOptions($match_track_options)
    {
        $this->container['match_track_options'] = $match_track_options;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}
