<?php
/**
 * TaskType
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * xServer
 *
 * PTV xServer 2.26.0 - 2.26 API document
 *
 * OpenAPI spec version: 2.26
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.34
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Model;
use \Swagger\Client\ObjectSerializer;

/**
 * TaskType Class Doc Comment
 *
 * @category Class
 * @description A type of task that can be carried out at a stop.    * &#x60;PICKUP&#x60; - An order is picked up.    * &#x60;DELIVERY&#x60; - An order is delivered.    * &#x60;VISIT&#x60; - A customer is visited.  Hint: Corresponding enum in xServer API documentation - com.ptvgroup.xserver.xtour.TaskType
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class TaskType
{
    /**
     * Possible values of this enum
     */
    const PICKUP = 'PICKUP';
const DELIVERY = 'DELIVERY';
const VISIT = 'VISIT';
    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::PICKUP,
self::DELIVERY,
self::VISIT,        ];
    }
}
