<?php
/**
 * Tour
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * xServer
 *
 * PTV xServer 2.26.0 - 2.26 API document
 *
 * OpenAPI spec version: 2.26
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.34
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Model;

use \ArrayAccess;
use \Swagger\Client\ObjectSerializer;

/**
 * Tour Class Doc Comment
 *
 * @category Class
 * @description As an operation schedule for a single vehicle, a tour provides the information which tasks are carried out in which order by the specified vehicle respectively its driver. There is at most one tour per vehicle. A tour contains a sequence of trips. See Tours and Trips. Hint: Corresponding type in xServer API documentation - com.ptvgroup.xserver.xtour.Tour
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class Tour implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'Tour';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'vehicle_id' => 'string',
'vehicle_start_location_id' => 'string',
'vehicle_end_location_id' => 'string',
'trips' => '\Swagger\Client\Model\Trip[]'    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'vehicle_id' => null,
'vehicle_start_location_id' => null,
'vehicle_end_location_id' => null,
'trips' => null    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'vehicle_id' => 'vehicleId',
'vehicle_start_location_id' => 'vehicleStartLocationId',
'vehicle_end_location_id' => 'vehicleEndLocationId',
'trips' => 'trips'    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'vehicle_id' => 'setVehicleId',
'vehicle_start_location_id' => 'setVehicleStartLocationId',
'vehicle_end_location_id' => 'setVehicleEndLocationId',
'trips' => 'setTrips'    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'vehicle_id' => 'getVehicleId',
'vehicle_start_location_id' => 'getVehicleStartLocationId',
'vehicle_end_location_id' => 'getVehicleEndLocationId',
'trips' => 'getTrips'    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['vehicle_id'] = isset($data['vehicle_id']) ? $data['vehicle_id'] : null;
        $this->container['vehicle_start_location_id'] = isset($data['vehicle_start_location_id']) ? $data['vehicle_start_location_id'] : null;
        $this->container['vehicle_end_location_id'] = isset($data['vehicle_end_location_id']) ? $data['vehicle_end_location_id'] : null;
        $this->container['trips'] = isset($data['trips']) ? $data['trips'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['vehicle_id'] === null) {
            $invalidProperties[] = "'vehicle_id' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets vehicle_id
     *
     * @return string
     */
    public function getVehicleId()
    {
        return $this->container['vehicle_id'];
    }

    /**
     * Sets vehicle_id
     *
     * @param string $vehicle_id The reference to the specific vehicle that is used to conduct this tour.
     *
     * @return $this
     */
    public function setVehicleId($vehicle_id)
    {
        $this->container['vehicle_id'] = $vehicle_id;

        return $this;
    }

    /**
     * Gets vehicle_start_location_id
     *
     * @return string
     */
    public function getVehicleStartLocationId()
    {
        return $this->container['vehicle_start_location_id'];
    }

    /**
     * Sets vehicle_start_location_id
     *
     * @param string $vehicle_start_location_id ID of this tour's vehicle's start location. This is always identical to the start location ID of the vehicle that is used to conduct this tour.
     *
     * @return $this
     */
    public function setVehicleStartLocationId($vehicle_start_location_id)
    {
        $this->container['vehicle_start_location_id'] = $vehicle_start_location_id;

        return $this;
    }

    /**
     * Gets vehicle_end_location_id
     *
     * @return string
     */
    public function getVehicleEndLocationId()
    {
        return $this->container['vehicle_end_location_id'];
    }

    /**
     * Sets vehicle_end_location_id
     *
     * @param string $vehicle_end_location_id ID of this tour's vehicle's end location. This is always identical to the end location ID of the vehicle that is used to conduct this tour.
     *
     * @return $this
     */
    public function setVehicleEndLocationId($vehicle_end_location_id)
    {
        $this->container['vehicle_end_location_id'] = $vehicle_end_location_id;

        return $this;
    }

    /**
     * Gets trips
     *
     * @return \Swagger\Client\Model\Trip[]
     */
    public function getTrips()
    {
        return $this->container['trips'];
    }

    /**
     * Sets trips
     *
     * @param \Swagger\Client\Model\Trip[] $trips trips
     *
     * @return $this
     */
    public function setTrips($trips)
    {
        $this->container['trips'] = $trips;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}
