<?php
/**
 * AccessTypeTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  ithings\ptvxserver
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * xServer
 *
 * PTV xServer 2.26.1 - 2.26 API document
 *
 * OpenAPI spec version: 2.26
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.34
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace ithings\ptvxserver;

/**
 * AccessTypeTest Class Doc Comment
 *
 * @category    Class
 * @description Indicates if a range of segments is entered or exited or both at the same time. The latter could be true, if the range consists of only few segments or nodes.    * &#x60;ENTER&#x60; - Indicates the entering of a range of segments.    * &#x60;EXIT&#x60; - Indicates the exiting of a range of segments.    * &#x60;PASS&#x60; - Indicates that the range is very small.  Hint: Corresponding enum in xServer API documentation - com.ptvgroup.xserver.xroute.AccessType
 * @package     ithings\ptvxserver
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class AccessTypeTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "AccessType"
     */
    public function testAccessType()
    {
    }
}
