<?php
/**
 * ClusterPlanningProfileTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  ithings\ptvxserver
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * xServer
 *
 * PTV xServer 2.26.1 - 2.26 API document
 *
 * OpenAPI spec version: 2.26
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.34
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace ithings\ptvxserver;

/**
 * ClusterPlanningProfileTest Class Doc Comment
 *
 * @category    Class
 * @description Defines parameters for cluster planning and optimization. Hint: Corresponding type in xServer API documentation - com.ptvgroup.xserver.clusterplanningprofile.ClusterPlanningProfile
 * @package     ithings\ptvxserver
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ClusterPlanningProfileTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "ClusterPlanningProfile"
     */
    public function testClusterPlanningProfile()
    {
    }

    /**
     * Test attribute "clustering"
     */
    public function testPropertyClustering()
    {
    }

    /**
     * Test attribute "covering"
     */
    public function testPropertyCovering()
    {
    }

    /**
     * Test attribute "visit_planning"
     */
    public function testPropertyVisitPlanning()
    {
    }

    /**
     * Test attribute "visit_sequencing"
     */
    public function testPropertyVisitSequencing()
    {
    }

    /**
     * Test attribute "solver_time_limit"
     */
    public function testPropertySolverTimeLimit()
    {
    }
}
