<?php
/**
 * ClusterReportTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  ithings\ptvxserver
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * xServer
 *
 * PTV xServer 2.26.1 - 2.26 API document
 *
 * OpenAPI spec version: 2.26
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.34
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace ithings\ptvxserver;

/**
 * ClusterReportTest Class Doc Comment
 *
 * @category    Class
 * @description Represents the summary of a cluster which was planned. Hint: Corresponding type in xServer API documentation - com.ptvgroup.xserver.xcluster.ClusterReport
 * @package     ithings\ptvxserver
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ClusterReportTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "ClusterReport"
     */
    public function testClusterReport()
    {
    }

    /**
     * Test attribute "cluster_id"
     */
    public function testPropertyClusterId()
    {
    }

    /**
     * Test attribute "total_activity"
     */
    public function testPropertyTotalActivity()
    {
    }

    /**
     * Test attribute "number_of_locations"
     */
    public function testPropertyNumberOfLocations()
    {
    }

    /**
     * Test attribute "estimated_travel_time_to_cluster"
     */
    public function testPropertyEstimatedTravelTimeToCluster()
    {
    }
}
