<?php
/**
 * CombinedTransportEventTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  ithings\ptvxserver
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * xServer
 *
 * PTV xServer 2.26.1 - 2.26 API document
 *
 * OpenAPI spec version: 2.26
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.34
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace ithings\ptvxserver;

/**
 * CombinedTransportEventTest Class Doc Comment
 *
 * @category    Class
 * @description CombinedTransportEvent
 * @package     ithings\ptvxserver
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class CombinedTransportEventTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "CombinedTransportEvent"
     */
    public function testCombinedTransportEvent()
    {
    }

    /**
     * Test attribute "combined_transport_id"
     */
    public function testPropertyCombinedTransportId()
    {
    }

    /**
     * Test attribute "combined_transport_name"
     */
    public function testPropertyCombinedTransportName()
    {
    }

    /**
     * Test attribute "combined_transport_type"
     */
    public function testPropertyCombinedTransportType()
    {
    }

    /**
     * Test attribute "access_type"
     */
    public function testPropertyAccessType()
    {
    }

    /**
     * Test attribute "related_event_index"
     */
    public function testPropertyRelatedEventIndex()
    {
    }
}
