<?php
/**
 * CountryListTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * xServer
 *
 * PTV xServer 2.26.0 - 2.26 API document
 *
 * OpenAPI spec version: 2.26
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.34
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * CountryListTest Class Doc Comment
 *
 * @category    Class
 * @description Defines the countries to which a style is assigned. The value can contain a single country, a comma separated list of countries, a continent code or a comma separated list of continent codes. The value \&quot;\\*\&quot; defines \&quot;every country\&quot;. See country codes. Pattern: (\\[A-Z\\]\\{2\\}|\\[A-Z\\]\\{2\\}-\\[A-Z0-9\\]\\{1,3\\})\\*(,\\[A-Z\\]\\{2\\}|,\\[A-Z\\]\\{2\\}-\\[A-Z0-9\\]\\{1,3\\})\\*|\\\\\\*. Hint: Corresponding unittype in xServer API documentation - com.ptvgroup.xserver.CountryList
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class CountryListTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "CountryList"
     */
    public function testCountryList()
    {
    }
}
