<?php
/**
 * CoveringTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * xServer
 *
 * PTV xServer 2.26.0 - 2.26 API document
 *
 * OpenAPI spec version: 2.26
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.34
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * CoveringTest Class Doc Comment
 *
 * @category    Class
 * @description Contains parameter values for the covering or reachability use cases. Hint: Corresponding type in xServer API documentation - com.ptvgroup.xserver.clusterplanningprofile.Covering
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class CoveringTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "Covering"
     */
    public function testCovering()
    {
    }

    /**
     * Test attribute "approximation_tolerance"
     */
    public function testPropertyApproximationTolerance()
    {
    }

    /**
     * Test attribute "perform_preprocessing_step"
     */
    public function testPropertyPerformPreprocessingStep()
    {
    }
}
