<?php
/**
 * CoverLocationsOptionsTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  ithings\ptvxserver
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * xServer
 *
 * PTV xServer 2.26.1 - 2.26 API document
 *
 * OpenAPI spec version: 2.26
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.34
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace ithings\ptvxserver;

/**
 * CoverLocationsOptionsTest Class Doc Comment
 *
 * @category    Class
 * @description Input parameters for the covering algorithm. Hint: Corresponding type in xServer API documentation - com.ptvgroup.xserver.xcluster.CoverLocationsOptions
 * @package     ithings\ptvxserver
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class CoverLocationsOptionsTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "CoverLocationsOptions"
     */
    public function testCoverLocationsOptions()
    {
    }

    /**
     * Test attribute "covering_horizon"
     */
    public function testPropertyCoveringHorizon()
    {
    }

    /**
     * Test attribute "optimization_goal"
     */
    public function testPropertyOptimizationGoal()
    {
    }

    /**
     * Test attribute "mandatory_location_ids"
     */
    public function testPropertyMandatoryLocationIds()
    {
    }

    /**
     * Test attribute "mandatory_cluster_ids"
     */
    public function testPropertyMandatoryClusterIds()
    {
    }
}
