<?php
/**
 * DistanceMatrixProgressStatusTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * xServer
 *
 * PTV xServer 2.26.0 - 2.26 API document
 *
 * OpenAPI spec version: 2.26
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.34
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * DistanceMatrixProgressStatusTest Class Doc Comment
 *
 * @category    Class
 * @description Possible status values for a distance matrix progress.    * &#x60;PREPROCESSING&#x60; - Indicates that some tasks have to be done before calculating the matrix. For example loading high-performance routing networks.    * &#x60;CALCULATING_MATRIX&#x60; - The actual progress of this state is available in DistanceMatrixProgress.calculationProgress.    * &#x60;DONE&#x60; - Indicates that the calculation of the distance matrix is finished.  Hint: Corresponding enum in xServer API documentation - com.ptvgroup.xserver.dima.ProgressStatus
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class DistanceMatrixProgressStatusTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "DistanceMatrixProgressStatus"
     */
    public function testDistanceMatrixProgressStatus()
    {
    }
}
