<?php
/**
 * EmissionValueScenarioFrenchCO2Decree20111336Test
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * xServer
 *
 * PTV xServer 2.26.0 - 2.26 API document
 *
 * OpenAPI spec version: 2.26
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.34
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * EmissionValueScenarioFrenchCO2Decree20111336Test Class Doc Comment
 *
 * @category    Class
 * @description EmissionValueScenarioFrenchCO2Decree20111336
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class EmissionValueScenarioFrenchCO2Decree20111336Test extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "EmissionValueScenarioFrenchCO2Decree20111336"
     */
    public function testEmissionValueScenarioFrenchCO2Decree20111336()
    {
    }

    /**
     * Test attribute "scenarios"
     */
    public function testPropertyScenarios()
    {
    }
}
