<?php
/**
 * EncodedGeometryTypeTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * xServer
 *
 * PTV xServer 2.26.0 - 2.26 API document
 *
 * OpenAPI spec version: 2.26
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.34
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * EncodedGeometryTypeTest Class Doc Comment
 *
 * @category    Class
 * @description Defines the encoding of response geometries.    * &#x60;PLAIN&#x60; - Response geometries shall be encoded using structured objects.    * &#x60;WKB&#x60; - Response geometries shall be encoded in WKB.    * &#x60;WKT&#x60; - Response geometries shall be encoded in WKT.    * &#x60;KML&#x60; - Response geometries shall be encoded in KML.    * &#x60;GEOJSON&#x60; - Response geometries shall be encoded in GeoJSON.  Hint: Corresponding enum in xServer API documentation - com.ptvgroup.xserver.geometry.EncodedGeometryType
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class EncodedGeometryTypeTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "EncodedGeometryType"
     */
    public function testEncodedGeometryType()
    {
    }
}
