<?php
/**
 * FuelTypeTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * xServer
 *
 * PTV xServer 2.26.0 - 2.26 API document
 *
 * OpenAPI spec version: 2.26
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.34
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * FuelTypeTest Class Doc Comment
 *
 * @category    Class
 * @description Defines the fuel type of the vehicle.    * &#x60;GASOLINE&#x60; - Gasoline (also known as petrol or benzine).    * &#x60;DIESEL&#x60; - Diesel.    * &#x60;COMPRESSED_NATURAL_GAS&#x60; - Compressed natural gas.    * &#x60;LIQUEFIED_PETROLEUM_GAS&#x60; - Liquefied petroleum gas.  Hint: Corresponding enum in xServer API documentation - com.ptvgroup.xserver.vehicleprofile.FuelType
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class FuelTypeTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "FuelType"
     */
    public function testFuelType()
    {
    }
}
