<?php
/**
 * GeometryStyleTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * xServer
 *
 * PTV xServer 2.26.0 - 2.26 API document
 *
 * OpenAPI spec version: 2.26
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.34
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * GeometryStyleTest Class Doc Comment
 *
 * @category    Class
 * @description Defines how to render geometries. Hint: Corresponding type in xServer API documentation - com.ptvgroup.xserver.renderingprofile.GeometryStyle
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class GeometryStyleTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "GeometryStyle"
     */
    public function testGeometryStyle()
    {
    }

    /**
     * Test attribute "render_level"
     */
    public function testPropertyRenderLevel()
    {
    }

    /**
     * Test attribute "stroke"
     */
    public function testPropertyStroke()
    {
    }

    /**
     * Test attribute "polygon"
     */
    public function testPropertyPolygon()
    {
    }

    /**
     * Test attribute "display_range"
     */
    public function testPropertyDisplayRange()
    {
    }
}
