<?php
/**
 * HighPerformanceRoutingNetworkDescriptionTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  ithings\ptvxserver
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * xServer
 *
 * PTV xServer 2.26.1 - 2.26 API document
 *
 * OpenAPI spec version: 2.26
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.34
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace ithings\ptvxserver;

/**
 * HighPerformanceRoutingNetworkDescriptionTest Class Doc Comment
 *
 * @category    Class
 * @description This type represents meta data about a high-performance routing network. Hint: Corresponding type in xServer API documentation - com.ptvgroup.xserver.xdata.HighPerformanceRoutingNetworkDescription
 * @package     ithings\ptvxserver
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class HighPerformanceRoutingNetworkDescriptionTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "HighPerformanceRoutingNetworkDescription"
     */
    public function testHighPerformanceRoutingNetworkDescription()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "label"
     */
    public function testPropertyLabel()
    {
    }

    /**
     * Test attribute "high_performance_routing_network_options"
     */
    public function testPropertyHighPerformanceRoutingNetworkOptions()
    {
    }

    /**
     * Test attribute "profile"
     */
    public function testPropertyProfile()
    {
    }

    /**
     * Test attribute "tenant"
     */
    public function testPropertyTenant()
    {
    }

    /**
     * Test attribute "scope"
     */
    public function testPropertyScope()
    {
    }

    /**
     * Test attribute "last_used_at"
     */
    public function testPropertyLastUsedAt()
    {
    }

    /**
     * Test attribute "size"
     */
    public function testPropertySize()
    {
    }
}
