<?php
/**
 * IncludedNetworkClassesTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * xServer
 *
 * PTV xServer 2.26.0 - 2.26 API document
 *
 * OpenAPI spec version: 2.26
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.34
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * IncludedNetworkClassesTest Class Doc Comment
 *
 * @category    Class
 * @description Defines a list of network classes to be included in the result. For more information about network classes see the type of the segment attribute network class. Hint: Corresponding type in xServer API documentation - com.ptvgroup.xserver.xdata.IncludedNetworkClasses
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class IncludedNetworkClassesTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "IncludedNetworkClasses"
     */
    public function testIncludedNetworkClasses()
    {
    }

    /**
     * Test attribute "included"
     */
    public function testPropertyIncluded()
    {
    }
}
