<?php
/**
 * ItemOrientationTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * xServer
 *
 * PTV xServer 2.26.0 - 2.26 API document
 *
 * OpenAPI spec version: 2.26
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.34
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * ItemOrientationTest Class Doc Comment
 *
 * @category    Class
 * @description Enumerates possible orientations. This is the full set of orientations that can lead to a unique shape of a cuboid object. Note that as only the shape is considered, things like whether an item is upside down have no influence on its orientation in this model. While we named the orientations, it might be simpler thinking of them as discrete orientations with no deeper meaning.    * &#x60;ORIGINAL&#x60; - Items is not re-oriented. Dimensions stay (x,y,z).    * &#x60;X&#x60; - Item is rotated around x-axis (widthwise) by +/-90 degrees compared to the original orientation. Dimensions are (x,z,y).    * &#x60;Y&#x60; - Item is rotated around y-axis (heightwise) by +/-90 degrees compared to the original orientation. Dimensions are (z,y,x).    * &#x60;Z&#x60; - Item is rotated around z-axis (lengthwise) by +/-90 degrees compared to the original orientation. Dimensions are (y,x,z).    * &#x60;XZ&#x60; - Item is rotated around x- then z-axis (width- then heightwise) by +/-90 degrees compared to the original orientation. Dimensions are (z,x,y).    * &#x60;YZ&#x60; - Item is rotated around its y- then z-axis (length- then heightwise) by +/-90 degrees compared to the original orientation. Dimensions are (y,z,x).  Hint: Corresponding enum in xServer API documentation - com.ptvgroup.xserver.xload.ItemOrientation
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ItemOrientationTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "ItemOrientation"
     */
    public function testItemOrientation()
    {
    }
}
