<?php
/**
 * MapSegmentTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * xServer
 *
 * PTV xServer 2.26.0 - 2.26 API document
 *
 * OpenAPI spec version: 2.26
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.34
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * MapSegmentTest Class Doc Comment
 *
 * @category    Class
 * @description A segment on the map. It represents a geographic location on a map, specified by its segment-id and may contain a polyline representation and additional descriptors like road name and number or combined transport attributes . Hint: Corresponding type in xServer API documentation - com.ptvgroup.xserver.xdata.MapSegment
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class MapSegmentTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "MapSegment"
     */
    public function testMapSegment()
    {
    }

    /**
     * Test attribute "type"
     */
    public function testPropertyType()
    {
    }

    /**
     * Test attribute "polyline"
     */
    public function testPropertyPolyline()
    {
    }

    /**
     * Test attribute "descriptors"
     */
    public function testPropertyDescriptors()
    {
    }

    /**
     * Test attribute "combined_transport"
     */
    public function testPropertyCombinedTransport()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }
}
