<?php
/**
 * MatchedPathTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  ithings\ptvxserver
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * xServer
 *
 * PTV xServer 2.26.1 - 2.26 API document
 *
 * OpenAPI spec version: 2.26
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.34
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace ithings\ptvxserver;

/**
 * MatchedPathTest Class Doc Comment
 *
 * @category    Class
 * @description Detailed information about a continuous part of a matched track. Hint: Corresponding type in xServer API documentation - com.ptvgroup.xserver.xmatch.MatchedPath
 * @package     ithings\ptvxserver
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class MatchedPathTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "MatchedPath"
     */
    public function testMatchedPath()
    {
    }

    /**
     * Test attribute "distance"
     */
    public function testPropertyDistance()
    {
    }

    /**
     * Test attribute "encoded_path"
     */
    public function testPropertyEncodedPath()
    {
    }

    /**
     * Test attribute "start_track_position_index"
     */
    public function testPropertyStartTrackPositionIndex()
    {
    }

    /**
     * Test attribute "end_track_position_index"
     */
    public function testPropertyEndTrackPositionIndex()
    {
    }
}
