<?php
/**
 * ModuleInstanceTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  ithings\ptvxserver
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * xServer
 *
 * PTV xServer 2.26.1 - 2.26 API document
 *
 * OpenAPI spec version: 2.26
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.34
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace ithings\ptvxserver;

/**
 * ModuleInstanceTest Class Doc Comment
 *
 * @category    Class
 * @description Represents a single backend instance and provides useful information. Hint: Corresponding type in xServer API documentation - com.ptvgroup.xserver.xruntime.ModuleInstance
 * @package     ithings\ptvxserver
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ModuleInstanceTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "ModuleInstance"
     */
    public function testModuleInstance()
    {
    }

    /**
     * Test attribute "instance_id"
     */
    public function testPropertyInstanceId()
    {
    }

    /**
     * Test attribute "services"
     */
    public function testPropertyServices()
    {
    }

    /**
     * Test attribute "uptime"
     */
    public function testPropertyUptime()
    {
    }

    /**
     * Test attribute "number_of_restarts"
     */
    public function testPropertyNumberOfRestarts()
    {
    }

    /**
     * Test attribute "in_use"
     */
    public function testPropertyInUse()
    {
    }

    /**
     * Test attribute "use_counter"
     */
    public function testPropertyUseCounter()
    {
    }

    /**
     * Test attribute "memory_statistics"
     */
    public function testPropertyMemoryStatistics()
    {
    }

    /**
     * Test attribute "state"
     */
    public function testPropertyState()
    {
    }
}
