<?php
/**
 * PenaltiesByNetworkClassTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  ithings\ptvxserver
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * xServer
 *
 * PTV xServer 2.26.1 - 2.26 API document
 *
 * OpenAPI spec version: 2.26
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.34
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace ithings\ptvxserver;

/**
 * PenaltiesByNetworkClassTest Class Doc Comment
 *
 * @category    Class
 * @description Defines the general penalty value for each network class. This is useful in order to force the routing algorithm to favor freeways over smaller roads. For more information about network classes see the type of the segment attribute network class. Hint: Corresponding type in xServer API documentation - com.ptvgroup.xserver.routingprofile.PenaltiesByNetworkClass
 * @package     ithings\ptvxserver
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class PenaltiesByNetworkClassTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "PenaltiesByNetworkClass"
     */
    public function testPenaltiesByNetworkClass()
    {
    }

    /**
     * Test attribute "penalties"
     */
    public function testPropertyPenalties()
    {
    }
}
