<?php
/**
 * PlanToursRequestTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  ithings\ptvxserver
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * xServer
 *
 * PTV xServer 2.26.1 - 2.26 API document
 *
 * OpenAPI spec version: 2.26
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.34
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace ithings\ptvxserver;

/**
 * PlanToursRequestTest Class Doc Comment
 *
 * @category    Class
 * @description PlanToursRequest
 * @package     ithings\ptvxserver
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class PlanToursRequestTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "PlanToursRequest"
     */
    public function testPlanToursRequest()
    {
    }

    /**
     * Test attribute "locations"
     */
    public function testPropertyLocations()
    {
    }

    /**
     * Test attribute "orders"
     */
    public function testPropertyOrders()
    {
    }

    /**
     * Test attribute "fleet"
     */
    public function testPropertyFleet()
    {
    }

    /**
     * Test attribute "input_plan"
     */
    public function testPropertyInputPlan()
    {
    }

    /**
     * Test attribute "plan_tours_options"
     */
    public function testPropertyPlanToursOptions()
    {
    }

    /**
     * Test attribute "distance_mode"
     */
    public function testPropertyDistanceMode()
    {
    }

    /**
     * Test attribute "store_request"
     */
    public function testPropertyStoreRequest()
    {
    }
}
