<?php
/**
 * PositionInTripTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * xServer
 *
 * PTV xServer 2.26.0 - 2.26 API document
 *
 * OpenAPI spec version: 2.26
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.34
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * PositionInTripTest Class Doc Comment
 *
 * @category    Class
 * @description Type of a specified position of a stop at a customer site within its trip.    * &#x60;FIRST_CUSTOMER_STOP&#x60; - A stop at a customer site with this position type has to be the very first customer stop in its trip.    * &#x60;LAST_CUSTOMER_STOP&#x60; - A stop at a customer site with this position type has to be the very last customer stop in its trip.  Hint: Corresponding enum in xServer API documentation - com.ptvgroup.xserver.xtour.PositionInTrip
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class PositionInTripTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "PositionInTrip"
     */
    public function testPositionInTrip()
    {
    }
}
