<?php
/**
 * RoadAttributesTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * xServer
 *
 * PTV xServer 2.26.0 - 2.26 API document
 *
 * OpenAPI spec version: 2.26
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.34
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * RoadAttributesTest Class Doc Comment
 *
 * @category    Class
 * @description Legal and physical attributes which describe the road segment in detail. Hint: Corresponding type in xServer API documentation - com.ptvgroup.xserver.segments.RoadAttributes
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class RoadAttributesTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "RoadAttributes"
     */
    public function testRoadAttributes()
    {
    }

    /**
     * Test attribute "prohibited"
     */
    public function testPropertyProhibited()
    {
    }

    /**
     * Test attribute "toll"
     */
    public function testPropertyToll()
    {
    }

    /**
     * Test attribute "urban"
     */
    public function testPropertyUrban()
    {
    }

    /**
     * Test attribute "residents_only"
     */
    public function testPropertyResidentsOnly()
    {
    }

    /**
     * Test attribute "pedestrian_zone"
     */
    public function testPropertyPedestrianZone()
    {
    }

    /**
     * Test attribute "one_way"
     */
    public function testPropertyOneWay()
    {
    }

    /**
     * Test attribute "roundabout"
     */
    public function testPropertyRoundabout()
    {
    }

    /**
     * Test attribute "ramp"
     */
    public function testPropertyRamp()
    {
    }

    /**
     * Test attribute "bridge"
     */
    public function testPropertyBridge()
    {
    }

    /**
     * Test attribute "tunnel"
     */
    public function testPropertyTunnel()
    {
    }

    /**
     * Test attribute "delivery_only"
     */
    public function testPropertyDeliveryOnly()
    {
    }

    /**
     * Test attribute "allowed_for_emergency"
     */
    public function testPropertyAllowedForEmergency()
    {
    }

    /**
     * Test attribute "low_emission_zone_type"
     */
    public function testPropertyLowEmissionZoneType()
    {
    }
}
