<?php
/**
 * RouteEventTypeTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  ithings\ptvxserver
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * xServer
 *
 * PTV xServer 2.26.1 - 2.26 API document
 *
 * OpenAPI spec version: 2.26
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.34
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace ithings\ptvxserver;

/**
 * RouteEventTypeTest Class Doc Comment
 *
 * @category    Class
 * @description Enumeration of the different RouteEvent types returned by a routing operation.    * &#x60;MANEUVER_EVENT&#x60; - This event type indicates that the driver has to take an action, e.g. turn left or right.    * &#x60;TOUR_EVENT&#x60; - This event type indicates that a tour information is available at this position.    * &#x60;TOLL_EVENT&#x60; - This event type indicates that a toll road is entered, exited or a toll booth is passed.    * &#x60;WAYPOINT_EVENT&#x60; - This event type indicates that a waypoint is reached by the route.    * &#x60;ROUTE_VIOLATION_EVENT&#x60; - This event type indicates that there is a route violation starting or ending at this position.    * &#x60;UTC_OFFSET_EVENT&#x60; - This event type indicates that the offset to UTC changes.    * &#x60;COUNTRY_EVENT&#x60; - This event type indicates that a border between countries or subdivisions is crossed, i.e. the country code changes.    * &#x60;COMBINED_TRANSPORT_EVENT&#x60; - This event type indicates that a combined transport is entered or exited.  Hint: Corresponding enum in xServer API documentation - com.ptvgroup.xserver.xroute.RouteEventType
 * @package     ithings\ptvxserver
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class RouteEventTypeTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "RouteEventType"
     */
    public function testRouteEventType()
    {
    }
}
