<?php
/**
 * SegmentsResultFieldsTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * xServer
 *
 * PTV xServer 2.26.0 - 2.26 API document
 *
 * OpenAPI spec version: 2.26
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.34
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * SegmentsResultFieldsTest Class Doc Comment
 *
 * @category    Class
 * @description Specifies to what extent segments shall be returned. Hint: Corresponding type in xServer API documentation - com.ptvgroup.xserver.xdata.SegmentsResultFields
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class SegmentsResultFieldsTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "SegmentsResultFields"
     */
    public function testSegmentsResultFields()
    {
    }

    /**
     * Test attribute "polyline"
     */
    public function testPropertyPolyline()
    {
    }

    /**
     * Test attribute "descriptors"
     */
    public function testPropertyDescriptors()
    {
    }

    /**
     * Test attribute "combined_transport"
     */
    public function testPropertyCombinedTransport()
    {
    }
}
