<?php
/**
 * SegmentTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  ithings\ptvxserver
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * xServer
 *
 * PTV xServer 2.26.1 - 2.26 API document
 *
 * OpenAPI spec version: 2.26
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.34
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace ithings\ptvxserver;

/**
 * SegmentTest Class Doc Comment
 *
 * @category    Class
 * @description A segment is defined by a start- and an end-node, which in turn will represent some geographic location. A segment may carry additional attributes and will add to the duration of a journey. Hint: Corresponding type in xServer API documentation - com.ptvgroup.xserver.xroute.Segment
 * @package     ithings\ptvxserver
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class SegmentTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "Segment"
     */
    public function testSegment()
    {
    }

    /**
     * Test attribute "start_node_index"
     */
    public function testPropertyStartNodeIndex()
    {
    }

    /**
     * Test attribute "end_node_index"
     */
    public function testPropertyEndNodeIndex()
    {
    }

    /**
     * Test attribute "distance"
     */
    public function testPropertyDistance()
    {
    }

    /**
     * Test attribute "travel_time"
     */
    public function testPropertyTravelTime()
    {
    }

    /**
     * Test attribute "travel_speed"
     */
    public function testPropertyTravelSpeed()
    {
    }

    /**
     * Test attribute "traffic_delay"
     */
    public function testPropertyTrafficDelay()
    {
    }

    /**
     * Test attribute "emissions"
     */
    public function testPropertyEmissions()
    {
    }

    /**
     * Test attribute "violated"
     */
    public function testPropertyViolated()
    {
    }

    /**
     * Test attribute "event_indices"
     */
    public function testPropertyEventIndices()
    {
    }

    /**
     * Test attribute "type"
     */
    public function testPropertyType()
    {
    }

    /**
     * Test attribute "polyline"
     */
    public function testPropertyPolyline()
    {
    }

    /**
     * Test attribute "attributes"
     */
    public function testPropertyAttributes()
    {
    }

    /**
     * Test attribute "combined_transport"
     */
    public function testPropertyCombinedTransport()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }
}
