<?php
/**
 * TimeRestrictionTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  ithings\ptvxserver
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * xServer
 *
 * PTV xServer 2.26.1 - 2.26 API document
 *
 * OpenAPI spec version: 2.26
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.34
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace ithings\ptvxserver;

/**
 * TimeRestrictionTest Class Doc Comment
 *
 * @category    Class
 * @description Defines the kinds of time restrictions present in Feature Layer data.    * &#x60;ALL&#x60; - All elements will be taken into account.    * &#x60;UNRESTRICTED&#x60; - Only elements without a restriction in validity will be taken into account.    * &#x60;RESTRICTED&#x60; - Only elements with a restriction in validity will be taken into account.  Hint: Corresponding enum in xServer API documentation - com.ptvgroup.xserver.renderingprofile.TimeRestriction
 * @package     ithings\ptvxserver
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class TimeRestrictionTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "TimeRestriction"
     */
    public function testTimeRestriction()
    {
    }
}
