<?php
/**
 * TollRoadTypeTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * xServer
 *
 * PTV xServer 2.26.0 - 2.26 API document
 *
 * OpenAPI spec version: 2.26
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.34
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * TollRoadTypeTest Class Doc Comment
 *
 * @category    Class
 * @description Represents reasons why toll is charged.    * &#x60;GENERAL&#x60; - A general toll road.    * &#x60;CITY&#x60; - The toll is charged because a whole city is subject to toll.    * &#x60;BRIDGE&#x60; - The toll is charged because of a bridge.    * &#x60;TUNNEL&#x60; - The toll is charged because of a tunnel.    * &#x60;FERRY&#x60; - The toll is charged because of a ferry.    * &#x60;MOUNTAIN_PASS&#x60; - The toll is charged because of a mountain pass.    * &#x60;UNSPECIFIED&#x60; - Fallback value to be substituted for enumeration values which were added in an API version that is newer than the request version. When using the current API, this value will never be returned.  Hint: Corresponding enum in xServer API documentation - com.ptvgroup.xserver.xroute.TollRoadType
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class TollRoadTypeTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "TollRoadType"
     */
    public function testTollRoadType()
    {
    }
}
