<?php
/**
 * ZoomLevelTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * xServer
 *
 * PTV xServer 2.26.0 - 2.26 API document
 *
 * OpenAPI spec version: 2.26
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.34
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * ZoomLevelTest Class Doc Comment
 *
 * @category    Class
 * @description Every map tile belongs to a zoom level z&#x3D;0, 1, 2, ??? . These levels are related to each other by a factor of two in scale. The zoom level also determines how many tiles are needed to display the entire world. At z&#x3D;0 the entire world is displayed in a single tile. At z&#x3D;1, 2x2&#x3D;4 tiles are needed to display the entire world, and so on. Fractional values are not possible. The zoom level is currently restricted to the range 0..22. Range: 0 ??? value ??? 22. Hint: Corresponding unittype in xServer API documentation - com.ptvgroup.xserver.ZoomLevel
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ZoomLevelTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "ZoomLevel"
     */
    public function testZoomLevel()
    {
    }
}
