<?php
/**
 * ZoomLevelRangeTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  ithings\ptvxserver
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * xServer
 *
 * PTV xServer 2.26.1 - 2.26 API document
 *
 * OpenAPI spec version: 2.26
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.34
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace ithings\ptvxserver;

/**
 * ZoomLevelRangeTest Class Doc Comment
 *
 * @category    Class
 * @description Defines a range of values between 0 and 24, describing a Google zoom level. Special values are NEVER or ALWAYS. The upper bound can be omitted, indicating a range with maximal Google zoom level, which can be rendered. Pattern: ALWAYS|NEVER|(\\[0-9\\]|1\\[0-9\\]|2\\[0-4\\])-(\\[0-9\\]|1\\[0-9\\]|2\\[0-4\\])\\{0,1\\}. Hint: Corresponding unittype in xServer API documentation - com.ptvgroup.xserver.ZoomLevelRange
 * @package     ithings\ptvxserver
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ZoomLevelRangeTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "ZoomLevelRange"
     */
    public function testZoomLevelRange()
    {
    }
}
