<?php
/**
 * XDataApiTest
 * PHP version 5
 *
 * @category Class
 * @package  ithings\ptvxserver
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * xServer
 *
 * PTV xServer 2.26.1 - 2.26 API document
 *
 * OpenAPI spec version: 2.26
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.34
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace ithings\ptvxserver;

use ithings\ptvxserver\Configuration;
use ithings\ptvxserver\ApiException;
use ithings\ptvxserver\ObjectSerializer;

/**
 * XDataApiTest Class Doc Comment
 *
 * @category Class
 * @package  ithings\ptvxserver
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class XDataApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for createContentSnapshot
     *
     * .
     *
     */
    public function testCreateContentSnapshot()
    {
    }

    /**
     * Test case for createFeatureLayer
     *
     * .
     *
     */
    public function testCreateFeatureLayer()
    {
    }

    /**
     * Test case for deleteContentSnapshot
     *
     * .
     *
     */
    public function testDeleteContentSnapshot()
    {
    }

    /**
     * Test case for deleteFeatureLayer
     *
     * .
     *
     */
    public function testDeleteFeatureLayer()
    {
    }

    /**
     * Test case for deleteHighPerformanceRoutingNetwork
     *
     * .
     *
     */
    public function testDeleteHighPerformanceRoutingNetwork()
    {
    }

    /**
     * Test case for fetchFeatureLayerResponse
     *
     * .
     *
     */
    public function testFetchFeatureLayerResponse()
    {
    }

    /**
     * Test case for fetchHighPerformanceRoutingNetworkResponse
     *
     * .
     *
     */
    public function testFetchHighPerformanceRoutingNetworkResponse()
    {
    }

    /**
     * Test case for getSegments
     *
     * .
     *
     */
    public function testGetSegments()
    {
    }

    /**
     * Test case for getTimeZone
     *
     * .
     *
     */
    public function testGetTimeZone()
    {
    }

    /**
     * Test case for listContentSnapshots
     *
     * .
     *
     */
    public function testListContentSnapshots()
    {
    }

    /**
     * Test case for listFeatureLayers
     *
     * .
     *
     */
    public function testListFeatureLayers()
    {
    }

    /**
     * Test case for listHighPerformanceRoutingNetworks
     *
     * .
     *
     */
    public function testListHighPerformanceRoutingNetworks()
    {
    }

    /**
     * Test case for startCreateFeatureLayer
     *
     * .
     *
     */
    public function testStartCreateFeatureLayer()
    {
    }

    /**
     * Test case for startCreateHighPerformanceRoutingNetwork
     *
     * .
     *
     */
    public function testStartCreateHighPerformanceRoutingNetwork()
    {
    }

    /**
     * Test case for timeZone
     *
     * .
     *
     */
    public function testTimeZone()
    {
    }
}
