<?php
/**
 * XRouteApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * xServer
 *
 * PTV xServer 2.26.0 - 2.26 API document
 *
 * OpenAPI spec version: 2.26
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.34
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use Swagger\Client\Configuration;
use Swagger\Client\ApiException;
use Swagger\Client\ObjectSerializer;

/**
 * XRouteApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class XRouteApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for calculateReachableAreas
     *
     * .
     *
     */
    public function testCalculateReachableAreas()
    {
    }

    /**
     * Test case for calculateReachableLocations
     *
     * .
     *
     */
    public function testCalculateReachableLocations()
    {
    }

    /**
     * Test case for calculateRoute
     *
     * .
     *
     */
    public function testCalculateRoute()
    {
    }

    /**
     * Test case for fetchReachableAreasResponse
     *
     * .
     *
     */
    public function testFetchReachableAreasResponse()
    {
    }

    /**
     * Test case for fetchReachableLocationsResponse
     *
     * .
     *
     */
    public function testFetchReachableLocationsResponse()
    {
    }

    /**
     * Test case for fetchRouteResponse
     *
     * .
     *
     */
    public function testFetchRouteResponse()
    {
    }

    /**
     * Test case for getProfile
     *
     * .
     *
     */
    public function testGetProfile()
    {
    }

    /**
     * Test case for route
     *
     * .
     *
     */
    public function testRoute()
    {
    }

    /**
     * Test case for startCalculateReachableAreas
     *
     * .
     *
     */
    public function testStartCalculateReachableAreas()
    {
    }

    /**
     * Test case for startCalculateReachableLocations
     *
     * .
     *
     */
    public function testStartCalculateReachableLocations()
    {
    }

    /**
     * Test case for startCalculateRoute
     *
     * .
     *
     */
    public function testStartCalculateRoute()
    {
    }
}
